# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `dev`")
spark.sql("USE SCHEMA `bronze`")

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from dev.bronze.sales

# COMMAND ----------

display(spark.sql("SELECT * FROM samples.wanderbricks.users"))

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from read_files("/Volumes/dev/bronze/raw/sales/")

# COMMAND ----------

# MAGIC %sql
# MAGIC select * , current_timestamp() as ingest_date,_metadata.file_name as path from stream read_files("/Volumes/dev/bronze/raw/sales")
